### ISSUE TITLE
Inverted containment issues

### ISSUE THREAD

**Issue by mdole** [timmywil/jquery.panzoom#136]
Hey guys,

I'm having some interesting issues with inverted containment. I'm working with a map application that uses a particular image as the background. There are two seperate issues I'm having, depending on whether I use a static image size or not:
1. Does panzoom support inverted containment with static image size but resizeable parent? If my image is the width of the window at the time I load the image and the parent is tied to window width at all times (e.g. resizeable), then I can't see the whole image if I shrink the window. Is this intended behavior?
2. If I tie the image width to window width in the same manner as the parent, I can no longer pan to the whole image when I zoom in--specifically, I have very limited vertical drag range. It's quite possible this is just an error in my code somewhere, but I haven't had an luck and thought you might have some experience with this type of issue.

Thanks for your help!

**Comment by mariothegreat** [comment]
Hello have you managed to solve this issue yet? I am having a similar problem. I am using this 
`  var $panzoom = element.panzoom({
                minScale: 1,
                maxScale: element.naturalWidth / element.clientWidth,
                contain: 'invert'
            });` 
in order to keep my image contained in is parent. even though it works perfectly fine on desktop computers it does not work as expected on mobile devices. It wont let me pan through the whole image and as a result it will show just a percentage of the image. However, if i zoom in the image it will let me pan further down the image. It is important to emphasise that this happens only on mobile and not with all images. The image that seems to have a problem is an infographic which is long in height.
