### ISSUE TITLE
Need support for rotation in 90 degree steps

### ISSUE THREAD

**Issue by robvdl** [timmywil/jquery.panzoom#178]
This can be done with CSS3

**Comment by david-hollifield** [comment]
+1. Would like to rotate an image and have panzoom be able to handle the new orientation. I can rotate the image, but panzoom overwrites the rotation transform as soon as you try to move the image. I can rotate the parent panzoom container, but the mouse has to be moved left/right instead of up/down.

**Comment by SamuelMichelRiad** [comment]
Any idea on how to accomplish this?

**Comment by mnwalker** [comment]
Still an issue, anyone solved this yet?

Have this on the container
transform: scale(1) rotate(180deg);

Pan left moves the image right and vice-versa.
