### ISSUE TITLE
Adding icons to panzoom element

### ISSUE THREAD

**Issue by zoltanseer** [timmywil/jquery.panzoom#179]
Hi. Is there a way to add icons (images) to the panzoom with presetted coordinates which moves and scales with the (background) panzoom element?
Thank!

**Comment by rpmaps** [comment]
I had a similar issue. I have "pins" placed on an underlying map image that need to remain positioned on the image but not scale in size on pan.  I have all of the pin locations set via css using the transform-origin property to set the transformation point to the base of my icons and referenced by ID in an array.  The pins are added to the html page in a div layered on the map.  Both the map and pins are within a parent div that is set as the $panzoom element.  This allows the tooltip icons to remain in position when the map is zoomed and panned.  In order to keep the icons at their original size, I've added a call to an external function at line 747 of jquery.panzoom.js immediately after the scale (matrix[0]) is set.  My external function simply parses my icon array and uses css transform: scale() (-webkit-transform, -ms-transform: scale()) to scale the icons as panzoom calls setMatrix to scale the $panzoom element.
