### ISSUE TITLE
Zoom: "focal" option doesn't work when "$set" was used on init

### ISSUE THREAD

**Issue by isaaclyman** [timmywil/jquery.panzoom#266]
### Subject
When the "$set" option is used to initialize panzoom, specifically on a child of the main panzoom element, the "focal" option of the zoom command malfunctions--the focal point is not frozen, and the zoom takes a parabolic shape on the Z-axis.

### Environment
Using jQuery 3.1.0, panzoom 3.2.0, on latest stable Chrome: 52.0.2743.116 m (64-bit).

### Steps to reproduce
See here: http://jsbin.com/xoquwa/edit?html,js,output.
I've taken the template JSbin and the "Use the mousewheel to zoom on a focal point" section from the demo page, and the only thing I changed was to add a "$set" parameter in the panzoom initialization. (I also added a few selectors to make everything work together).

### Expected behavior
The focal point should stay in the same screen position while the panzoom element zooms in and out.

### Actual behaviour
The focal point moves dramatically, and the viewport zooms in and out along a parabolic curve.

**Comment by timmywil** [comment]
Thanks for opening an issue, but I'm not sure the focal option should support a $set in that way, since the $set element(s) themselves can even be somewhere else on the page, making expected behavior very difficult to define. The `$set` option is more for [additional elements on which to set transforms](http://jsbin.com/bivaxuq/1/edit?html,js,output). If you're going to just have one element, the set should really be #panzoom, not #tiger. Dimensions are always based on the panzoom element, which is good for most cases and bad for yours. I'm not sure your use case, but I suggest leaving the panzoom element as the $set if at all possible.

**Comment by isaaclyman** [comment]
My use case: I have a big parent div that I want to receive the panzoom events (it covers the whole screen), and a smaller child element (a tree chart) that I want to be panned and zoomed. This gives the illusion of an interactive field of infinite size.

Thanks for explaining why panzoom isn't intended to work this way. I'll figure out an alternate design for the page.
