### ISSUE TITLE
Linearzoom false option not behaving as expected

### ISSUE THREAD

**Issue by godavem** [timmywil/jquery.panzoom#276]
### Subject of the issue
If I set the linearZoom to false as below, the zooming still behaves linearly (is becomes progressively slower once you get to beyond a zoom of 1.5 or 2).

$("#rec2").panzoom({
		linearZoom: false,
		panOnlyWhenZoomed: false,
		maxScale: 8,
		contain: false
});

### Your environment
* version of jquery.panzoom
v3.2.2
* version of jquery
3.1 (http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js)
* which browser and its version
Safari on iPhone 5 (iOS 9.3.5)

### Steps to reproduce
Tell us how to reproduce this issue. 
Working demo: http://www.ancestryux.net/demo/rd/home-brim.html
1. Swipe up to activate full screen mode and trigger panzoom.
2. Pinch zoom

### Expected behaviour
Expect the zooming to roughly track directly to where the users fingers are pointing on the image being zoomed while pinching out and in.

### Actual behaviour
Zooming slows as you scale the image up, so the fingers start slipping on the image.

### Kudos
This is a fantastic plug-in. I love it! Thanks for all of your hard work and diligence in making it come to life. It works like a dream. Super-responsive and just what I needed to get my project up and going. You are totally awesome!!

**Comment by timmywil** [comment]
Thanks for opening an issue! It's hard to tell what's going on in the demo, or what to focus on in the code. Perhaps you could create a reduced test case on [jsbin.com](http://jsbin.com).

Keep in mind that calculating zoom in a non-linear fashion does not guarantee that zooming will not seem to slow down at points. The default setting is false, which guarantees that the zoom will increment by larger values, but that still may not be large enough in your case. The `increment` option is also there to increase the increments.

I'll close this issue for now because it's been a while and the action item is unclear. I will reopen pending further investigation. Thanks!
