### ISSUE TITLE
How can I save/export current state of an paned/zoomed object?

### ISSUE THREAD

**Issue by aetherwu** [timmywil/jquery.panzoom#287]
### Subject of the issue
I would like to save/export a current state to a json object so that I can apply it to later or to another object.
Could $elem.panzoom('option') work for me (which seems not currently)?

I've tried:
var v = $elem.panzoom('option')
but it returns undefined :(

**Comment by aetherwu** [comment]
OK...

So I should compile these two...

STEP 1:
var saved_state = $elem.panzoom("getMatrix");
// => [1, 0, 0, 1, 0, 0]

STEP2:
// Flip the element upside down
$elem.panzoom("setMatrix",  saved_state);

It is little counter-intuitive but still works for me. But these two methods are 'basically' internal as the author indicated in README.

**Comment by teropernu** [comment]
Ahoy,
Also wondering this same thing. Did you get it solved somehow?

So, here's my problem.
I want to save a location on a floor plan with getMatrix and later show it with setMatrix. The problem is that the container sizes vary due to mobile and desktop usage.

So my setMatrix and getMatrix with the same location and zoom level are:

"capture-desktop.jpg"
$('#pohjakuva').panzoom("getMatrix");
Array [ "1", "0", "0", "1", "-222", "107" ]

![capture-desktop](https://user-images.githubusercontent.com/36243559/35937856-28e25ac2-0c50-11e8-8a19-24a89241bc5a.JPG)


"capture_mobile.jpg"
$('#pohjakuva').panzoom("getMatrix");
Array [ "1", "0", "0", "1", "-392", "-66" ]

![capture-mobile](https://user-images.githubusercontent.com/36243559/35937857-290782ac-0c50-11e8-8526-8b353c2d2549.JPG)
